# Use RunPod CUDA-enabled base image to resolve CUDA_HOME issues
# FROM runpod/base:0.7.0-cuda1281-ubuntu2404
FROM nvidia/cuda:13.0.0-cudnn-devel-ubuntu24.04

# Install uv
COPY --from=ghcr.io/astral-sh/uv:latest /uv /uvx /bin/

# Change the working directory to the `app` directory
WORKDIR /app

# Copy the project into the image
ADD . /app

# Install additional requirements
RUN uv pip install -r requirements.txt

# Runpod SDK
RUN uv pip install --no-cache-dir runpod

# Start the container
CMD ["uv", "run", "rp_handler.py"]
